[project]
name = "medllm-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.1.1",
    "gliner>=0.2.22",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
